import { createElement } from 'lwc';
import AdVic_CartAccountSwitcher from 'c/adVic_CartAccountSwitcher';

describe('c-ad-vic-cart-account-switcher', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-ad-vic-cart-account-switcher', {
            is: AdVic_CartAccountSwitcher
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});